name:                tsp-functional
version:             0.1.0.0
github:              "githubuser/tsp-functional"
license:             BSD3
author:              "Jainam Chirag Shah"
maintainer:          "jcshah98@gmail.com"
copyright:           "2021 Jainam Chirag Shah"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tsp-functional#readme>

dependencies:
- base >= 4.7 && < 5
- parallel
- random

library:
  source-dirs: src

executables:
  tsp-functional-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -eventlog
    dependencies:
    - tsp-functional

tests:
  tsp-functional-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tsp-functional
